#!/bin/bash


function readlink_rec {
	res="$(readlink $1 || echo $1)"
	if [ $res = $1 ]
	then
		echo $res
	else
		readlink_rec $res
	fi
}


root=`dirname "$(readlink_rec $0)"`
lib="$root/platform-partition/target/lib"

compiler="$lib/compiler-1.0-SNAPSHOT.jar"

platform="$root/platform-partition/target/platform-partition-1.0-SNAPSHOT.jar"

if [ -f "$compiler" ]
then
	java -cp "$compiler:$lib/*:$platform" se.lth.cs.tycho.compiler.Main  "partition" "$@"
else
	echo "Tycho is not compiled. Please, run \"mvn install\" to compile Tycho."
	exit 1
fi
