#!/bin/bash


function readlink_rec {
	res="$(readlink $1 || echo $1)"
	if [ $res = $1 ]
	then
		echo $res
	else
		readlink_rec $res
	fi
}


root=`dirname "$(readlink_rec $0)"`
lib="$root/platform-partition/target/lib"
libs="$lib/core-1.0-SNAPSHOT.jar"
libs="$libs:$lib/multij-core-0.1.jar"
libs="$libs:$lib/platform-core-1.0-SNAPSHOT.jar"
libs="$libs:$lib/gurobi-jar-8.1.0.jar"

compiler="$lib/compiler-1.0-SNAPSHOT.jar"

platform="$lib/../platform-partition-1.0-SNAPSHOT.jar"


if [ -f "$compiler" ]
then
	java -cp "$compiler:$platform:$libs" se.lth.cs.tycho.compiler.Main  "$@"
else
	echo "Tycho is not compiled. Please, run \"mvn install\" to compile Tycho."
	exit 1
fi
